dist: xenial   # required for Python >= 3.7
language: python
env:
  - IMAGESIZE=true
  - IMAGESIZE=false
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3"
# command to install dependencies
install:
  - imagesize=''
  - pip install -U coveralls pytest pytest-cov coverage codecov
  - if [[ $IMAGESIZE == true ]] ; then imagesize='[imagesize]' ; fi
  - pip install -e ".${imagesize}"
# command to run tests
script: py.test
after_success:
  - coveralls
  - codecov
